-- INSERT INTO Produto (code, description, type, value_provider, amount) VALUES (404, 'Notebook', 1, 3300.90, 1);
-- INSERT INTO Produto (code, description, type, value_provider, amount) VALUES (200, 'Televisao', 1, 2700.01, 1);
-- INSERT INTO Produto (code, description, type, value_provider, amount) VALUES (500, 'Mouse', 1, 400.00, 1);
-- INSERT INTO Produto (code, description, type, value_provider, amount) VALUES (402, 'Monitor', 1, 1200.10, 1);
-- INSERT INTO Produto (code, description, type, value_provider, amount) VALUES (202, 'Fone de Ouvido', 1, 300.10, 1)